# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routing.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'routing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrouting.proto\x12\x07transit\"P\n\x0cRouteRequest\x12\x13\n\x0bsource_stop\x18\x01 \x01(\r\x12\x13\n\x0btarget_stop\x18\x02 \x01(\r\x12\x16\n\x0e\x64\x65parture_time\x18\x03 \x01(\r\"i\n\x03Leg\x12\x12\n\nboard_stop\x18\x01 \x01(\r\x12\x13\n\x0b\x61light_stop\x18\x02 \x01(\r\x12\x10\n\x08route_id\x18\x03 \x01(\r\x12\x12\n\nboard_time\x18\x04 \x01(\r\x12\x13\n\x0b\x61light_time\x18\x05 \x01(\r\"A\n\rRouteResponse\x12\x1f\n\titinerary\x18\x01 \x03(\x0b\x32\x0c.transit.Leg\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32T\n\rRoutingEngine\x12\x43\n\x12GetEarliestArrival\x12\x15.transit.RouteRequest\x1a\x16.transit.RouteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTEREQUEST']._serialized_start=26
  _globals['_ROUTEREQUEST']._serialized_end=106
  _globals['_LEG']._serialized_start=108
  _globals['_LEG']._serialized_end=213
  _globals['_ROUTERESPONSE']._serialized_start=215
  _globals['_ROUTERESPONSE']._serialized_end=280
  _globals['_ROUTINGENGINE']._serialized_start=282
  _globals['_ROUTINGENGINE']._serialized_end=366
# @@protoc_insertion_point(module_scope)
