services:
  redis:
    image: redis:alpine
    container_name: transit-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  engine:
    build:
      context: ..
      dockerfile: infra/Dockerfile.cpp
    container_name: transit-engine
    depends_on:
      - redis
    ports:
      - "50051:50051"
    restart: unless-stopped

  telemetry:
    build:
      context: ..
      dockerfile: infra/Dockerfile.python
    container_name: transit-telemetry
    depends_on:
      - redis
    restart: unless-stopped

  gateway:
    build:
      context: ..
      dockerfile: infra/Dockerfile.gateway
    container_name: transit-gateway
    depends_on:
      - engine
      - redis
    ports:
      - "8000:8000"
    restart: unless-stopped
