FROM python:3.9-slim

WORKDIR /app

COPY telemetry/requirements.txt /app/requirements.txt
COPY telemetry/live_stream.py /app/live_stream.py

RUN pip install --no-cache-dir -r /app/requirements.txt

ENTRYPOINT ["python", "-u", "/app/live_stream.py"]
